# fly.toml app configuration file generated for delicate-dew-3615 on 2023-07-20T07:43:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-dew-3615"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
